apiVersion: v1
kind: Secret
metadata:
  name: kubenews-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_USER: kubenews
  POSTGRES_DB: kubenews
  DB_DATABASE: kubenews
  DB_USERNAME: kubenews
  DB_PASSWORD: CHANGE_ME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubenews-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kubenews-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: kubenews-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: fabricioveronez/kube-news:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: kubenews-secret
              key: DB_DATABASE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubenews-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: kubenews-secret
              key: DB_USERNAME
        - name: DB_HOST
          value: postgre
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
